remote_theme: mmistakes/minimal-mistakes@4.24.0
minimal_mistakes_skin: "dark"

defaults:
  - scope:
      path: ""
    values:
      layout: single
  - scope:
      path: "docs"
    values:
      sidebar:
        nav: "docs"
