name: clang-format check
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  formatting-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run clang-format style check.
      uses: DoozyX/clang-format-lint-action@v0.16.2
      with:
        source: 'src'
        extensions: 'h,cpp'
        clangFormatVersion: 16
